// Sidekicks core forge — venv. Zero runtime dependencies.
import {
  existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync, copyFileSync,
  statSync, lstatSync, realpathSync, readlinkSync, rmSync, symlinkSync, chmodSync,
  renameSync, openSync, closeSync,
} from "node:fs";
import { join, dirname, relative, resolve, basename, sep, isAbsolute } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createHash, randomBytes } from "node:crypto";
import { spawnSync } from "node:child_process";
import { configurationInventory } from "../core-lifecycle/config-templates.mjs";
import { resolveFrameworkPreset } from "../skill-package/framework-preset.mjs";
import {
  projectSkillRuntime,
  projectedSourceHashes,
  RUNTIME_EXCLUDED_DIRS,
} from "../skill-package/runtime-projection.mjs";
import { ASSETS, isWindows } from './_shared.mjs';

export function loadJsonAsset(file, fallback) {
  const p = join(ASSETS, file);
  if (!existsSync(p)) return fallback;
  try { return JSON.parse(readFileSync(p, "utf8")); } catch { return fallback; }
}

export function pythonExe() {
  for (const cand of isWindows ? ["python", "python3"] : ["python3", "python"]) {
    if (spawnSync(cand, ["--version"], { encoding: "utf8" }).status === 0) return cand;
  }
  return null;
}

export function stdlibNames(py) {
  if (py) {
    const r = spawnSync(py, ["-c",
      "import sys,json;print(json.dumps(sorted(getattr(sys,'stdlib_module_names',()))))"],
      { encoding: "utf8" });
    if (r.status === 0) {
      try {
        const arr = JSON.parse(r.stdout);
        if (Array.isArray(arr) && arr.length) return new Set(arr);
      } catch { /* fall through to the bundled list */ }
    }
  }
  return new Set(loadJsonAsset("py-stdlib.json", []));
}

export function scanPythonImports(dirs) {
  const modules = new Map();    // module -> Set(file)
  const localNames = new Set(); // sibling .py modules / packages living inside the skills
  const pyFiles = [];

  const walk = (dir) => {
    if (!existsSync(dir)) return;
    for (const e of readdirSync(dir).sort()) {
      const p = join(dir, e);
      let st;
      try { st = lstatSync(p); } catch { continue; }
      if (st.isSymbolicLink()) continue;
      if (st.isDirectory()) {
        if (e === "__pycache__" || e === ".venv") continue;
        if (existsSync(join(p, "__init__.py"))) localNames.add(e);
        walk(p);
      } else if (e.endsWith(".py")) {
        pyFiles.push(p);
        localNames.add(e.slice(0, -3));
      }
    }
  };
  for (const d of dirs) walk(d);

  const importRe = /^\s*(?:import\s+([A-Za-z_][\w.]*)|from\s+([A-Za-z_][\w.]*)\s+import)/;
  for (const f of pyFiles) {
    let text;
    try { text = readFileSync(f, "utf8"); } catch { continue; }
    for (const line of text.split(/\r?\n/)) {
      const m = importRe.exec(line);
      if (!m) continue;
      const top = (m[1] ?? m[2]).split(".")[0];
      if (!top || top === "__future__") continue;
      if (!modules.has(top)) modules.set(top, new Set());
      modules.get(top).add(f);
    }
  }
  return { modules, localNames };
}

export function sourceFreeze(repoRoot) {
  const pip = join(repoRoot, ".venv", isWindows ? "Scripts" : "bin", isWindows ? "pip.exe" : "pip");
  if (!existsSync(pip)) return {};
  const r = spawnSync(pip, ["freeze"], { encoding: "utf8" });
  if (r.status !== 0) return {};
  const map = {};
  for (const line of r.stdout.split(/\r?\n/)) {
    const m = /^([A-Za-z0-9._-]+)==(.+)$/.exec(line.trim());
    if (m) map[m[1].toLowerCase().replace(/[-_.]+/g, "-")] = `${m[1]}==${m[2]}`;
  }
  return map;
}

export function resolveRequirements(repoRoot, skillDirs) {
  const py = pythonExe();
  const stdlib = stdlibNames(py);
  const modMap = loadJsonAsset("module-distribution.json", {});
  const freeze = sourceFreeze(repoRoot);
  const { modules, localNames } = scanPythonImports(skillDirs);

  const pinned = new Set();
  const unpinned = new Set();
  const unknown = [];
  const skipped = [];

  for (const [mod, files] of [...modules.entries()].sort()) {
    if (stdlib.has(mod)) { skipped.push(`${mod} (stdlib)`); continue; }
    if (localNames.has(mod)) { skipped.push(`${mod} (skill-local)`); continue; }
    const dist = modMap[mod];
    if (dist === null) { skipped.push(`${mod} (mapped to nothing on purpose)`); continue; }
    if (!dist) { unknown.push({ module: mod, files: [...files].slice(0, 3) }); continue; }
    const key = dist.toLowerCase().replace(/[-_.]+/g, "-");
    if (freeze[key]) pinned.add(freeze[key]);
    else unpinned.add(dist);
  }
  return { pinned: [...pinned].sort(), unpinned: [...unpinned].sort(), unknown, skipped: skipped.sort() };
}

export function venvBin(runtimeRoot) {
  return join(runtimeRoot, ".venv", isWindows ? "Scripts" : "bin");
}

export function buildVenv(runtimeRoot, reqs, { install = true, force = false } = {}) {
  const lines = [
    "# Generated by sk-publish-core — do not hand-edit; re-run `inherit venv` instead.",
    "# Versions are pinned from the source repo's .venv (pip freeze) so the runtime reproduces",
    "# the exact package set its skills were developed against.",
    ...reqs.pinned,
    ...reqs.unpinned,
  ];
  const reqPath = join(runtimeRoot, "requirements.txt");
  const next = `${lines.join("\n")}\n`;
  const prev = existsSync(reqPath) ? readFileSync(reqPath, "utf8") : null;
  writeFileSync(reqPath, next, "utf8");

  if (!install) return { ok: true, installed: false, note: "requirements.txt written; venv not built (--no-venv)" };

  // Nothing to do when the package set is unchanged and the venv is already usable.
  // pip install is the slowest step here; re-running it on every patch buys nothing.
  if (!force && prev === next && existsSync(join(venvBin(runtimeRoot), isWindows ? "pip.exe" : "pip"))) {
    return { ok: true, installed: true, note: "requirements unchanged — venv left as-is" };
  }

  const py = pythonExe();
  if (!py) return { ok: false, installed: false, note: "no python on PATH — requirements.txt written, venv NOT built" };

  const venvDir = join(runtimeRoot, ".venv");
  // Presence of the DIRECTORY is not proof of a venv. An interrupted or failed earlier build leaves an
  // empty .venv/ behind, and skipping creation on that basis produced a runtime that reported
  // "venv created but pip is missing" forever — the directory existed, so it was never rebuilt.
  // The interpreter is the real signal; a venv without one is rubble and gets replaced.
  const venvPython = join(venvBin(runtimeRoot), isWindows ? "python.exe" : "python");
  if (existsSync(venvDir) && !existsSync(venvPython)) {
    rmSync(venvDir, { recursive: true, force: true });
  }
  if (!existsSync(venvDir)) {
    const r = spawnSync(py, ["-m", "venv", venvDir], { encoding: "utf8", stdio: "pipe" });
    if (r.status !== 0) {
      return { ok: false, installed: false, note: `python -m venv failed: ${(r.stderr || "").trim().split("\n").pop()}` };
    }
  }

  const pkgs = [...reqs.pinned, ...reqs.unpinned];
  if (pkgs.length === 0) return { ok: true, installed: true, note: "venv created; no third-party packages needed" };

  const pip = join(venvBin(runtimeRoot), isWindows ? "pip.exe" : "pip");
  if (!existsSync(pip)) return { ok: false, installed: false, note: "venv created but pip is missing" };

  const runPip = () => spawnSync(pip, ["install", "--disable-pip-version-check", "-q", "-r", reqPath],
    { encoding: "utf8", stdio: "pipe" });

  let r = runPip();

  // A pinned version can be absent from PyPI — the source venv may hold a local, pre-release, or
  // withdrawn build (observed: pip freeze reports ImageIO==2.37.3, which PyPI does not serve).
  // pip resolves the whole file at once, so ONE unsatisfiable pin fails EVERY package. Relax only
  // the pins pip names as unsatisfiable and retry, keeping every other version exact.
  const relaxed = [];
  for (let round = 0; r.status !== 0 && round < 5; round++) {
    const blob = `${r.stderr || ""}\n${r.stdout || ""}`;
    const names = [...blob.matchAll(/requirement\s+([A-Za-z0-9._-]+)(?:==|>=|<=)/gi)].map((m) => m[1]);
    const fresh = [...new Set(names)].filter((n) => !relaxed.includes(n));
    if (!fresh.length) break;                       // failure is something else — stop retrying
    relaxed.push(...fresh);

    const norm = (s) => s.toLowerCase().replace(/[-_.]+/g, "-");
    const relaxSet = new Set(relaxed.map(norm));
    const relax = (spec) => {
      const name = spec.split("==")[0];
      return relaxSet.has(norm(name)) ? name : spec;
    };
    writeFileSync(reqPath, `${[
      "# Generated by sk-publish-core — do not hand-edit; re-run `inherit venv` instead.",
      "# Versions are pinned from the source repo's .venv (pip freeze).",
      `# UNPINNED (the source venv's version is not available on PyPI): ${relaxed.join(", ")}`,
      ...reqs.pinned.map(relax),
      ...reqs.unpinned,
    ].join("\n")}\n`, "utf8");
    r = runPip();
  }

  if (r.status !== 0) {
    const tail = (r.stderr || r.stdout || "").trim().split("\n")
      .filter((l) => /^(ERROR|error:)/.test(l.trim())).slice(0, 2).join(" | ")
      || (r.stderr || r.stdout || "").trim().split("\n").slice(-2).join(" | ");
    return { ok: false, installed: false, relaxed, note: `pip install failed (offline?): ${tail}` };
  }
  const note = `installed ${pkgs.length} package(s) into the runtime's own .venv`;
  return relaxed.length
    ? { ok: true, installed: true, relaxed, note: `${note}; UNPINNED ${relaxed.join(", ")} — the source venv's version is not on PyPI, so the runtime got the newest available instead` }
    : { ok: true, installed: true, relaxed, note };
}
