#!/usr/bin/env python3
"""Install and run the Codex/Bedrock auto-compaction compatibility layer.

LiteLLM 1.83.x converts Responses API ``instructions`` and every historical
``developer`` item into separate system messages. Strict Qwen chat templates
reject a system message after conversation history, so the first request after
Codex local compaction fails with HTTP 500.

The generated launcher starts a loopback proxy for its Codex child. The proxy
moves every system/developer input item into the single top-level
``instructions`` value before forwarding the request. No API key is stored or
logged; the Authorization header simply passes through to the configured
gateway.
"""

from __future__ import annotations

import argparse
import http.client
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import importlib
import json
import os
from pathlib import Path
import shutil
import shlex
import stat
import subprocess
import sys
import tempfile
import threading
from typing import Any
from urllib.parse import urlsplit


MARKER = "Generated by scripts/codex-bedrock-compaction-compat.py"
PROFILE_NAME = "bedrock-llm-lean.config.toml"
FEATURE_KEY = "remote_compaction_v2"
HOP_BY_HOP = {
    "connection",
    "keep-alive",
    "proxy-authenticate",
    "proxy-authorization",
    "te",
    "trailer",
    "transfer-encoding",
    "upgrade",
}


def platform_name(value: str | None = None) -> str:
    if value:
        return value
    return "windows" if os.name == "nt" else "posix"


def launcher_path(home: Path, platform: str) -> Path:
    if platform == "windows":
        return home / "AppData" / "Local" / "Microsoft" / "WindowsApps" / "codex-bedrock-lean.cmd"
    return home / ".local" / "bin" / "codex-bedrock-lean"


def profile_path(home: Path) -> Path:
    return home / ".codex" / PROFILE_NAME


def render_launcher(repo: Path, platform: str) -> str:
    script_rel_posix = "scripts/codex-bedrock-compaction-compat.py"
    if platform == "windows":
        default_repo = str(repo).replace("%", "%%")
        script_rel_windows = script_rel_posix.replace("/", "\\")
        return "".join(
            [
                "@echo off\r\n",
                f"rem {MARKER}; re-run its apply command after the Bedrock host setup.\r\n",
                f'set "DEFAULT_SIDEKICKS_REPO={default_repo}"\r\n',
                'if "%SIDEKICKS_REPO%"=="" set "SIDEKICKS_REPO=%DEFAULT_SIDEKICKS_REPO%"\r\n',
                'set "PY=%SIDEKICKS_REPO%\\.venv\\Scripts\\python.exe"\r\n',
                'if not exist "%PY%" set "PY=python"\r\n',
                f'"%PY%" "%SIDEKICKS_REPO%\\{script_rel_windows}" launch '
                '--repo "%SIDEKICKS_REPO%" -- %*\r\n',
            ]
        )

    quoted_repo = shlex.quote(str(repo))
    return "\n".join(
        [
            "#!/bin/sh",
            f"# codex-bedrock-lean - {MARKER}.",
            "# Re-run its apply command after the Bedrock host setup regenerates this file.",
            f"DEFAULT_SIDEKICKS_REPO={quoted_repo}",
            'REPO="${SIDEKICKS_REPO:-$DEFAULT_SIDEKICKS_REPO}"',
            'PY="$REPO/.venv/bin/python"; [ -x "$PY" ] || PY=python3',
            f'exec "$PY" "$REPO/{script_rel_posix}" launch --repo "$REPO" -- "$@"',
            "",
        ]
    )


def ensure_local_compaction(profile: str) -> str:
    """Set remote_compaction_v2=false without reformatting unrelated TOML."""
    newline = "\r\n" if "\r\n" in profile else "\n"
    lines = profile.splitlines()
    feature_index = next((i for i, line in enumerate(lines) if line.strip() == "[features]"), None)

    if feature_index is None:
        if lines and lines[-1].strip():
            lines.append("")
        lines.extend(["[features]", f"{FEATURE_KEY} = false"])
    else:
        section_end = len(lines)
        for i in range(feature_index + 1, len(lines)):
            if lines[i].strip().startswith("["):
                section_end = i
                break
        key_index = next(
            (
                i
                for i in range(feature_index + 1, section_end)
                if lines[i].split("=", 1)[0].strip() == FEATURE_KEY
            ),
            None,
        )
        if key_index is None:
            insertion_index = section_end
            while insertion_index > feature_index + 1 and not lines[insertion_index - 1].strip():
                insertion_index -= 1
            lines.insert(insertion_index, f"{FEATURE_KEY} = false")
        else:
            lines[key_index] = f"{FEATURE_KEY} = false"

    return newline.join(lines) + newline


def atomic_write(path: Path, content: str, *, executable: bool = False) -> bool:
    encoded = content.encode("utf-8")
    if path.exists() and path.read_bytes() == encoded:
        if executable and os.name != "nt" and not path.stat().st_mode & stat.S_IXUSR:
            os.chmod(path, path.stat().st_mode | 0o111)
            return True
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(encoded)
        if executable and os.name != "nt":
            os.chmod(temporary, 0o755)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)
    return True


def backup_once(path: Path) -> None:
    backup = path.with_name(f"{path.name}.pre-compaction-compat.bak")
    if path.exists() and not backup.exists():
        backup.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, backup)


def install(repo: Path, home: Path, platform: str) -> list[str]:
    host_setup = repo / ".agents" / "skills" / "sk-cli-executor" / "scripts" / "bedrock_llm_host_setup.py"
    if not host_setup.is_file():
        raise RuntimeError(f"Sidekicks Bedrock host setup was not found: {host_setup}")

    profile = profile_path(home)
    if not profile.is_file():
        raise RuntimeError(
            f"Codex lean profile was not found: {profile}\n"
            "Run bedrock_llm_host_setup.py --apply first, then run this installer again."
        )

    launcher = launcher_path(home, platform)
    backup_once(launcher)
    backup_once(profile)

    changed: list[str] = []
    if atomic_write(launcher, render_launcher(repo, platform), executable=platform == "posix"):
        changed.append(str(launcher))
    updated_profile = ensure_local_compaction(profile.read_text(encoding="utf-8"))
    if atomic_write(profile, updated_profile):
        changed.append(str(profile))
    return changed


def state(repo: Path, home: Path, platform: str) -> dict[str, Any]:
    launcher = launcher_path(home, platform)
    profile = profile_path(home)
    expected_launcher = render_launcher(repo, platform)
    launcher_ok = launcher.is_file() and launcher.read_bytes() == expected_launcher.encode("utf-8")
    profile_text = profile.read_text(encoding="utf-8") if profile.is_file() else ""
    profile_ok = ensure_local_compaction(profile_text) == profile_text if profile_text else False
    return {
        "ok": launcher_ok and profile_ok,
        "launcher": str(launcher),
        "launcher_ok": launcher_ok,
        "profile": str(profile),
        "profile_ok": profile_ok,
    }


def _content_text(content: Any) -> str:
    if isinstance(content, str):
        return content
    if not isinstance(content, list):
        return ""
    parts: list[str] = []
    for part in content:
        if not isinstance(part, dict):
            continue
        for key in ("text", "input_text", "output_text"):
            value = part.get(key)
            if isinstance(value, str) and value:
                parts.append(value)
                break
    return "\n".join(parts)


def merge_developer_into_instructions(payload: dict[str, Any]) -> tuple[dict[str, Any], int]:
    input_items = payload.get("input")
    if not isinstance(input_items, list):
        return payload, 0

    instruction_parts: list[str] = []
    existing = payload.get("instructions")
    if isinstance(existing, str) and existing:
        instruction_parts.append(existing)

    retained: list[Any] = []
    merged = 0
    for item in input_items:
        if isinstance(item, dict) and item.get("role") in {"developer", "system"}:
            text = _content_text(item.get("content"))
            if text:
                instruction_parts.append(text)
            merged += 1
            continue
        retained.append(item)

    if not merged:
        return payload, 0
    rewritten = dict(payload)
    rewritten["instructions"] = "\n\n".join(instruction_parts)
    rewritten["input"] = retained
    return rewritten, merged


class CompatServer(ThreadingHTTPServer):
    daemon_threads = True
    allow_reuse_address = True

    def __init__(self, address: tuple[str, int], upstream_base: str):
        super().__init__(address, CompatHandler)
        self.upstream = urlsplit(upstream_base.rstrip("/"))


class CompatHandler(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def log_message(self, format: str, *args: Any) -> None:
        if os.environ.get("CODEX_BEDROCK_PROXY_DEBUG") == "1":
            super().log_message(format, *args)

    def do_GET(self) -> None:  # noqa: N802 - BaseHTTPRequestHandler interface
        self._forward()

    def do_POST(self) -> None:  # noqa: N802 - BaseHTTPRequestHandler interface
        self._forward()

    def _forward(self) -> None:
        server = self.server
        assert isinstance(server, CompatServer)
        upstream = server.upstream
        length = int(self.headers.get("Content-Length", "0"))
        body = self.rfile.read(length) if length else None
        transformed = False

        if body is not None and self.path.split("?", 1)[0].rstrip("/").endswith("/responses"):
            encoding = self.headers.get("Content-Encoding", "").lower()
            if encoding:
                self.send_error(415, f"unsupported request content encoding: {encoding}")
                return
            try:
                payload = json.loads(body)
                payload, merged = merge_developer_into_instructions(payload)
                if merged:
                    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode()
                    transformed = True
            except (UnicodeDecodeError, json.JSONDecodeError, TypeError) as exc:
                self.send_error(400, f"invalid Responses JSON: {exc}")
                return

        headers: dict[str, str] = {}
        for key, value in self.headers.items():
            lower = key.lower()
            if lower in HOP_BY_HOP or lower in {"host", "content-length"}:
                continue
            if transformed and lower == "content-encoding":
                continue
            headers[key] = value
        if body is not None:
            headers["Content-Length"] = str(len(body))

        upstream_prefix = upstream.path.rstrip("/")
        if upstream_prefix.endswith("/v1") and self.path.startswith("/v1"):
            target_path = upstream_prefix + self.path[3:]
        else:
            target_path = upstream_prefix + self.path

        connection_class = http.client.HTTPSConnection if upstream.scheme == "https" else http.client.HTTPConnection
        connection = connection_class(upstream.hostname, upstream.port, timeout=6100)
        try:
            connection.request(self.command, target_path, body=body, headers=headers)
            response = connection.getresponse()
            streaming = response.getheader("Content-Type", "").lower().startswith("text/event-stream")
            self.send_response(response.status, response.reason)
            for key, value in response.getheaders():
                if key.lower() not in HOP_BY_HOP and key.lower() != "content-length":
                    self.send_header(key, value)
            if streaming:
                self.send_header("Connection", "close")
                self.end_headers()
                while True:
                    chunk = response.read1(65536)
                    if not chunk:
                        break
                    self.wfile.write(chunk)
                    self.wfile.flush()
                self.close_connection = True
            else:
                response_body = response.read()
                self.send_header("Content-Length", str(len(response_body)))
                self.end_headers()
                if response_body:
                    self.wfile.write(response_body)
        except (OSError, http.client.HTTPException) as exc:
            if not self.wfile.closed:
                self.send_error(502, f"Bedrock gateway proxy error: {exc}")
        finally:
            connection.close()


def load_upstream(repo: Path) -> str:
    scripts = repo / ".agents" / "skills" / "sk-cli-executor" / "scripts"
    sys.path.insert(0, str(scripts))
    module = importlib.import_module("bedrock_llm_host_setup")
    config = module._resolve_config()
    return str(config["base_url"])


def launch(repo: Path, codex_args: list[str]) -> int:
    upstream = load_upstream(repo)
    server = CompatServer(("127.0.0.1", 0), upstream)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    local_base = f"http://127.0.0.1:{server.server_address[1]}/v1"

    setup = repo / ".agents" / "skills" / "sk-cli-executor" / "scripts" / "bedrock_llm_host_setup.py"
    python = repo / ".venv" / ("Scripts/python.exe" if os.name == "nt" else "bin/python")
    if not python.exists():
        python = Path(sys.executable)
    args = codex_args[1:] if codex_args[:1] == ["--"] else codex_args
    command = [
        str(python),
        str(setup),
        "launch",
        "--lean",
        "codex",
        "--",
        "-c",
        f'model_providers.bedrock-llm.base_url="{local_base}"',
        *args,
    ]
    try:
        return subprocess.call(command)
    except KeyboardInterrupt:
        return 130
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=2)


def self_test() -> int:
    original = {
        "instructions": "base",
        "input": [
            {"role": "user", "content": [{"type": "input_text", "text": "first"}]},
            {"role": "developer", "content": [{"type": "input_text", "text": "rules"}]},
            {"role": "system", "content": []},
            {"role": "user", "content": [{"type": "input_text", "text": "last"}]},
        ],
    }
    rewritten, merged = merge_developer_into_instructions(original)
    assert merged == 2
    assert rewritten["instructions"] == "base\n\nrules"
    assert [item["role"] for item in rewritten["input"]] == ["user", "user"]
    assert original["input"][1]["role"] == "developer"
    assert FEATURE_KEY in ensure_local_compaction("[features]\nhooks = false\n")
    assert "Scripts\\python.exe" in render_launcher(Path("C:/sidekicks"), "windows")
    assert ".venv/bin/python" in render_launcher(Path("/src/sidekicks"), "posix")
    print("codex-bedrock compaction compatibility self-test: OK")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="action")

    def add_location_options(command: argparse.ArgumentParser) -> None:
        command.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
        command.add_argument("--home", type=Path, default=Path.home())
        command.add_argument("--platform", choices=["posix", "windows"])

    check = subparsers.add_parser("check", help="report whether the compatibility layer is installed")
    add_location_options(check)
    check.add_argument("--json", action="store_true")

    apply = subparsers.add_parser("apply", help="install or repair the launcher and Codex profile")
    add_location_options(apply)

    launch_parser = subparsers.add_parser("launch", help="run Codex through the loopback compatibility proxy")
    launch_parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    launch_parser.add_argument("codex_args", nargs=argparse.REMAINDER)

    subparsers.add_parser("self-test", help="run network-free transformation checks")
    arguments = sys.argv[1:] or ["check"]
    return parser.parse_args(arguments)


def main() -> int:
    options = parse_args()
    if options.action == "self-test":
        return self_test()
    repo = options.repo.resolve()
    if options.action == "launch":
        return launch(repo, options.codex_args)
    platform = platform_name(options.platform)
    if options.action == "apply":
        changed = install(repo, options.home.resolve(), platform)
        print("codex-bedrock compaction compatibility: " + ("updated" if changed else "already current"))
        for path in changed:
            print(f"  {path}")
        return 0

    result = state(repo, options.home.resolve(), platform)
    if options.json:
        print(json.dumps(result, indent=2))
    else:
        print(f"launcher: {'ok' if result['launcher_ok'] else 'needs apply'} — {result['launcher']}")
        print(f"profile:  {'ok' if result['profile_ok'] else 'needs apply'} — {result['profile']}")
    return 0 if result["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
